const THEMES = [
    'acid',
    'aqua',
    'black',
    'buisness',
    'bumblebee',
    'cmyk',
    'coffee',
    'corporate',
    'cupcake',
    'cyberpunk',
    'dark',
    'dracula',
    'emerald',
    'fantasy',
    'forest',
    'garden',
    'halloween',
    'lemonade',
    'light',
    'lowfi',
    'luxury',
    'night',
    'pastel',
    'retro',
    'synthwave',
    'valentine',
    'winter',
    'wireframe',
];

const HREFS = {
    daisyui: 'https://daisyui.com/docs/themes/',
    repo: 'https://github.com/devmegan/theme-switch',
}
export { THEMES, HREFS };